# Generated by Django 2.2.14 on 2020-09-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donarmodel',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='donarmodel',
            name='bgroup',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('o+', 'o+'), ('o-', 'o-')], default='A+', max_length=70),
        ),
    ]
