# Generated by Django 2.2.14 on 2020-09-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200910_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='donarmodel',
            name='image',
            field=models.FileField(default='Not Uploaded', upload_to=''),
        ),
    ]
